config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users, only: [:new, :show, :create]
  get "/users/:user_id/libraries", to: "library_users#index", as: 'user_libraries'
  post "/libraries/:library_id/users", to: "library_users#create", as: "new_user_library" 

  resources :libraries, only: [:index, :new, :show]
  post "/libraries", to: "libraries#create"
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :library_users, dependent: :destroy
  has_many :users, through: :library_users
end

app/models/library_user.rb
class LibraryUser < ApplicationRecord
  belongs_to :user
  belongs_to :library
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :library_users, dependent: :destroy
  has_many :libraries, through: :library_users

  validates :email, :password, :first_name, :last_name, presence: true
  validates :email, uniqueness: true

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libs = Library.all
  end

  def show
    lib_id = params[:id]
    @lib = Library.find_by_id(lib_id)
    @users = @lib.users
  end

  def new
    @lib = Library.new
  end

  def create
    lib = Library.create(lib_params)
    if lib.save
      redirect_to library_path(lib)
    end
  end

  private

  def lib_params
    params.require(:library).permit(:name, :floor_count, :floor_area)
  end
end

app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @libs = @user.libraries
  end
  def create
    lib_id = params[:library_id]
    lib = Library.find(lib_id)
    lib.users << current_user
    redirect_to user_libraries_path(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)

    @user = User.confirm(user_params)
    if @user 
      login(@user)
      flash[:notice] = "Successfully logged in." 
      redirect_to @user
    else
      flash[:error] = "Incorrect email or password."
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:error] = "Successfully logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    user_id = params[:id]
    @user = User.find(user_id)
    if @user != current_user
      flash[:error] = "Not Your Page!"
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if !@user.errors.messages.empty?
      flash[:error] = @user.errors.full_messages.join(", ")
    end
    login(@user)
    redirect_to @user
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login user
    session[:user_id]  = user.id
    @current_user = user
  end
    
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = nil
    session[:user_id] = nil
  end

  def logged_in?
    return !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
    <li><%= link_to "home", root_path%></li>
      <% if current_user %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Create Account", new_user_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
    </ul>

    <% flash.each do |name, msg| %>
      <p>
        <small> <%= name.capitalize %>: <%= msg %> </small>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/libraries/index.html.erb
<% @libs.each do |lib| %>
  <div>
    <h3><%= lib.name %></h3>
    <%= link_to "Our Site", library_path(lib)%>
    <% if current_user%>
      <%= button_to "Become a Member", new_user_library_path(lib)%> 
    <%end%>
  </div>
  <hr>
<% end %>

<%= link_to "Add a Library to Our List", new_library_path%>

app/views/libraries/new.html.erb
<%= form_for @lib do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
<%= f.number_field :floor_area, placeholder: "Floor Area"  %>
<%= f.number_field :floor_count, placeholder: "Floor Count"  %>
<%= f.submit %>
<%end%>

app/views/libraries/show.html.erb
<h2><%= @lib.name%></h2>

<h3>Members:</h3>
<ul>
  <% @users.each do |user| %>
    <li> <%= user.first_name%> </li>
  <%end%>
</ul>

<%= link_to "back", libraries_path%>

app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries</div>

<ul>
  <% @libs.each do |lib| %>   
    <li><%= lib.name %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Awesome Page</h1>
<p><%= @users.length%> Current Users!</p>
<h3><%= link_to "Search Libraries", libraries_path%></h3>

app/views/users/new.html.erb
<%= form_for @user do |f|%>
  <%= f.text_field :first_name, placeholder: "first name"%>
  <br>
  <%= f.text_field :last_name, placeholder: "last name"%>
  <br>
  <%= f.text_field :email, placeholder: "email"%>
  <br>
  <%= f.text_field :password, placeholder: "password"%>
  <br>
  <%= f.submit "Submit"%>
<%end%>

<%= link_to "back", users_path%>

app/views/users/show.html.erb
<h1><%= @user.first_name%>'s Page</h1>
<h3><%= @user.email%></h3>
<%= link_to "My Libraries", user_libraries_path(@user)%>
<br>
<%= link_to "Search Libraries", libraries_path%>